- name: Update repositories
  hosts: podman
  tasks:
    - name: Update apk
      become: true
      ansible.builtin.apt:
        update_cache: yes
- name: install packages
  hosts: podman
  tasks:
    - name: install packages
      ansible.builtin.apt: name={{ item }} update_cache=yes state=latest
      become: true
      with_items:
        - git
        - vim
        - podman
- name: Pull Podman image and Push it to my Azr
  hosts: podman
  vars_files:
    - "{{ playbook_dir }}/vars/azr_vars.yml"
  tasks:
    - name: Login to registry AZR gauladell
      containers.podman.podman_login:
        username: "{{ AZR_USER }}"
        password: "{{ AZR_TOKEN }}"
        registry: "{{ AZR_REGISTRY }}"
    - name: Pull Redis image from registry
      podman_image:
         name: "mcr.microsoft.com/oss/bitnami/redis:6.0.8"
         force: true        
    - name: Pull Voting image from registry
      podman_image:
         name: "mcr.microsoft.com/azuredocs/azure-vote-front:v1"         
         force: true
    - name: Push Redis image to registry 
      podman_image:
         name: "redis:6.0.8"
         push: true
         pull: false
         force: true                
         username: "{{ AZR_USER }}"
         password: "{{ AZR_TOKEN }}"
         push_args:
           dest: "{{ AZR_REGISTRY}}/redis:6.0.8"
    - name: Push Voting Api image to registry 
      podman_image:
         name: "azure-vote-front:v1"
         push: true
         pull: false
         force: true                
         username: "{{ AZR_USER }}"
         password: "{{ AZR_TOKEN }}"
         push_args:
           dest: "{{ AZR_REGISTRY}}/azure-vote-front:v1"
- name: Run Kubernetes 
  hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/vars/azr_vars.yml"
  tasks:
    - name: Create a Deployment by reading the definition from a local file
      k8s:
        kubeconfig: ~/.kube/config
        namespace: default
        state: present
        src: ../kubernetes/kube-example.yml