- name: Update repositories
  hosts: podman
  tasks:
    - name: Update apk
      become: true
      ansible.builtin.apt:
        update_cache: yes
- name: install packages
  hosts: podman
  tasks:
    - name: install packages
      ansible.builtin.apt: name={{ item }} update_cache=yes state=latest
      become: true
      with_items:
        - git
        - vim
        - podman
- name: Pull Podman image and Run it 
  hosts: podman
  vars_files:
    - "{{ playbook_dir }}/vars/azr_vars.yml"
  tasks:
    - name: Login to registry AZR gauladell
      containers.podman.podman_login:
        username: "{{ AZR_USER }}"
        password: "{{ AZR_TOKEN }}"
        registry: "{{ AZR_REGISTRY }}"
    - name: Pull image from registry
      podman_image:
         name: docker.io/nginx
    - name: Push image to registry 
      podman_image:
         name: nginx
         push: true
         username: "{{ AZR_USER }}"
         password: "{{ AZR_TOKEN }}"
         push_args:
           dest: "{{ AZR_REGISTRY}}/nginx"
    - name: "Allow the nginx container to run in the 80 port of the host"
      become: true
      become_user: root
      become_method: sudo
      ansible.posix.sysctl:
        name: net.ipv4.ip_unprivileged_port_start
        value: "80"
        sysctl_set: true
        reload: true
    - name: Running httpd image.
      containers.podman.podman_container:
        name:  "cp2-podman-app"
        image: "{{ AZR_IMAGE }}"
        ports:
          - "80:80"
          - "443:443"       
        state: started
        generate_systemd:
          restart_policy: always
   
         
